# Generated by Django 3.2.7 on 2021-10-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='marks',
            new_name='max_marks',
        ),
    ]
