# Generated by Django 3.2.7 on 2021-10-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_marks_exam_max_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='teacher',
        ),
    ]
