# Generated by Django 3.2.7 on 2021-10-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_exam_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ms',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
