# Generated by Django 3.2.7 on 2021-11-01 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_ms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='classSection',
        ),
    ]
