# Generated by Django 3.2.7 on 2021-11-01 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20211021_1331'),
        ('exam', '0005_remove_exam_classsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamHeldSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.subject')),
            ],
        ),
    ]
