# Generated by Django 3.2.7 on 2021-11-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_examheldsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
    ]
