# Generated by Django 3.2.7 on 2021-11-10 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_exam_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='exam',
        ),
        migrations.AddField(
            model_name='score',
            name='exam_held',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='exam.examheldsubject'),
            preserve_default=False,
        ),
    ]
