# Generated by Django 3.2.7 on 2021-11-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20211110_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examheldsubject',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
