# Generated by Django 3.2.7 on 2021-11-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_student_dob'),
        ('exam', '0010_alter_examheldsubject_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='exam_held',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examheldsubject'),
        ),
        migrations.AlterField(
            model_name='score',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
