# Generated by Django 3.2.8 on 2021-10-21 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attendance',
        ),
    ]
