# Generated by Django 3.2.8 on 2021-10-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attendance',
        ),
    ]
