# Generated by Django 3.2.8 on 2021-10-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_delete_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='score',
            name='stu',
        ),
        migrations.DeleteModel(
            name='exam',
        ),
        migrations.DeleteModel(
            name='score',
        ),
    ]
