# Generated by Django 3.2.7 on 2021-11-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20211021_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
