# Generated by Django 3.2.8 on 2021-10-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='school',
        ),
    ]
