# Generated by Django 3.2.8 on 2021-10-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=2000)),
                ('due_date', models.DateField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
