# Generated by Django 3.2.8 on 2021-10-23 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20211021_1331'),
        ('homework', '0002_alter_homework_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='teacher.teacher'),
        ),
    ]
