# Generated by Django 3.2.8 on 2021-10-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20211021_1331'),
        ('homework', '0003_homework_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='user',
        ),
        migrations.AlterField(
            model_name='homework',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.classsection'),
        ),
    ]
