# Generated by Django 3.2.8 on 2021-10-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_auto_20211024_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='Class',
        ),
    ]
