# Generated by Django 3.2.8 on 2021-10-24 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20211021_1331'),
        ('homework', '0006_student_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_homework',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='teacher.subject'),
            preserve_default=False,
        ),
    ]
