# Generated by Django 3.2.8 on 2021-11-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_homeworksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='sub_desc',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
