# Generated by Django 3.2.8 on 2021-11-12 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0009_homeworksubmission_sub_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.student_homework'),
        ),
    ]
