# Generated by Django 3.2.8 on 2021-10-23 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20211021_1331'),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='students',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='user',
        ),
        migrations.CreateModel(
            name='receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notice.notice')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.classsection')),
            ],
        ),
    ]
