# Generated by Django 3.2.8 on 2021-11-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_notice_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='posted_by',
        ),
    ]
