# Generated by Django 3.2.8 on 2021-11-01 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0009_auto_20211021_1331'),
        ('notice', '0004_remove_notice_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='posted_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receiver',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.notice'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.classsection'),
        ),
    ]
