# Generated by Django 3.2.8 on 2021-11-01 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0005_auto_20211101_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='receiver',
            name='posted_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
