# Generated by Django 3.2.7 on 2021-11-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_auto_20211101_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiver',
            name='posted_by',
        ),
    ]
