# Generated by Django 3.2.8 on 2021-10-16 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_school'),
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='superadmin.school'),
            preserve_default=False,
        ),
    ]
