# Generated by Django 3.2.7 on 2021-11-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
