# Generated by Django 3.2.7 on 2021-11-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ad_no',
        ),
    ]
