# Generated by Django 3.2.7 on 2021-11-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_student_ad_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='add_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
