# Generated by Django 3.2.7 on 2021-11-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_add_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
